#[http]
#bind="0.0.0.0"
#port=7880

[mqtt]
serverAddress="mqtt://127.0.0.1:1884"
clientid="iotmonitorfhome2"


[device_esp04]
watchTimeOut=60
helloTopic="home/esp04"
watchTopics="home/esp04/sensors/#"
stateTopics="home/esp04/actuators/#"


